form_login:
    path:     /login
    defaults: { _controller: FormLoginBundle:Login:login }

form_login_check:
    path:     /login_check
    defaults: { _controller: FormLoginBundle:Login:loginCheck }

form_login_homepage:
    path:     /
    defaults: { _controller: FormLoginBundle:Login:afterLogin }

form_login_custom_target_path:
    path:     /foo
    defaults: { _controller: FormLoginBundle:Login:afterLogin }

form_login_default_target_path:
    path:     /profile
    defaults: { _controller: FormLoginBundle:Login:afterLogin }

form_login_redirect_to_protected_resource_after_login:
    path:     /protected_resource
    defaults: { _controller: FormLoginBundle:Login:afterLogin }

highly_protected_resource:
    path:     /highly_protected_resource

secured-by-one-ip:
    path:     /secured-by-one-ip

secured-by-two-ips:
    path:     /secured-by-two-ips

form_logout:
    path:     /logout_path

form_secure_action:
    path:     /secure-but-not-covered-by-access-control
    defaults: { _controller: FormLoginBundle:Login:secure }

protected-via-expression:
    path:     /protected-via-expression
session_welcome:
    path:     /session
    defaults: { _controller: TestBundle:Session:welcome }

session_welcome_name:
    path:     /session/{name}
    defaults: { _controller: TestBundle:Session:welcome }

session_logout:
    path:     /session_logout
    defaults: { _controller: TestBundle:Session:logout}

session_setflash:
    path:     /session_setflash/{message}
    defaults: { _controller: TestBundle:Session:setFlash}

session_showflash:
    path:     /session_showflash
    defaults: { _controller: TestBundle:Session:showFlash}

profiler:
    path:     /profiler
    defaults: { _controller: TestBundle:Profiler:index }

subrequest_index:
    path:     /subrequest/{_locale}.{_format}
    defaults: { _controller: TestBundle:SubRequest:index, _format: "html" }
    schemes:  [https]

subrequest_fragment_error:
    path:     /subrequest/fragment/error/{_locale}.{_format}
    defaults: { _controller: TestBundle:SubRequest:fragmentError, _format: "html" }
    schemes:  [http]

subrequest_fragment:
    path:     /subrequest/fragment/{_locale}.{_format}
    defaults: { _controller: TestBundle:SubRequest:fragment, _format: "html" }
    schemes:  [http]

fragment_home:
    path:     /fragment_home
    defaults: { _controller: TestBundle:Fragment:index, _format: txt }

fragment_inlined:
    path:     /fragment_inlined
    defaults: { _controller: TestBundle:Fragment:inlined }

